# Generated by Django 3.0.3 on 2020-03-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regdt', models.DateTimeField(auto_now_add=True)),
                ('gov', models.CharField(blank=True, max_length=50, null=True, verbose_name='المحافظة')),
                ('wly', models.CharField(blank=True, max_length=50, null=True, verbose_name='الولاية')),
                ('vill', models.CharField(blank=True, max_length=50, null=True, verbose_name='القرية')),
                ('stre', models.CharField(blank=True, max_length=50, null=True, verbose_name='الشارع')),
                ('ftype', models.CharField(blank=True, choices=[('أيتام', 'أيتام'), ('دخل محدود', 'دخل محدود'), ('أسرة ضمانية', 'أسرة ضمانية'), ('عجز', 'عجز')], default='دخل محدود', max_length=50, null=True, verbose_name='فئة الأسرة')),
                ('hasname', models.CharField(blank=True, max_length=300, null=True, verbose_name='إسم الزوج')),
                ('hasnat', models.CharField(blank=True, max_length=50, null=True, verbose_name='جنسية الزوج')),
                ('hasid', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم المدني')),
                ('hasmobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='هاتف الزوج')),
                ('hasstatus', models.CharField(max_length=50, null=True, verbose_name='حالة الزوج')),
                ('hasstatus_others', models.TextField(blank=True, default='مسجون', null=True, verbose_name='أخري')),
                ('wfname', models.CharField(blank=True, max_length=300, null=True, verbose_name='إسم الزوجة')),
                ('wfnat', models.CharField(blank=True, max_length=50, null=True, verbose_name='جنسية الزوجة')),
                ('wfid', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم المدني')),
                ('wfmobile', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الهاتف')),
                ('wfstatus', models.CharField(blank=True, choices=[('ربة منزل', 'ربة منزل'), ('أرملة', 'أرملة'), ('هجر', 'هجر'), ('عجز', 'عجز'), ('مريضة', 'مريضة'), ('متوفاة', 'متوفاة'), ('مطلقة', 'مطلقة')], default='أرملة', max_length=300, null=True, verbose_name='حالة الزوجة')),
                ('wfstatus_others', models.TextField(null=True, verbose_name='أخرى')),
                ('orph', models.CharField(max_length=300, null=True, verbose_name='إسم ولي أمر الأيتام أو الوكيل')),
                ('orph_id', models.CharField(max_length=50, null=True, verbose_name='الرقم المدني')),
                ('orph_rel', models.CharField(max_length=50, null=True, verbose_name='صلة القرابة')),
                ('orphmobile', models.CharField(max_length=50, null=True, verbose_name='رقم الهاتف')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_report', models.TextField(blank=True, null=True, verbose_name='تقرير الباحث الإجتماعي عن حالة الأسرة')),
                ('recome', models.TextField(blank=True, null=True, verbose_name='إقتراحات الباحث')),
                ('res_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='إسم الباحث')),
                ('res_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البحث')),
                ('res_tel', models.CharField(blank=True, max_length=30, null=True, verbose_name='رقم الهاتف')),
                ('comm_rec', models.TextField(blank=True, null=True, verbose_name='توصية اللجنة')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyNeeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_supply', models.BooleanField(default=False, verbose_name='كفالة مواد غذائية')),
                ('orp_care', models.BooleanField(default=False, verbose_name='كفالة أسر أيتام')),
                ('elec_needs', models.TextField(blank=True, null=True, verbose_name='المواد الكهربائية')),
                ('furn_needs', models.TextField(blank=True, null=True, verbose_name='الأثاث المنزلي')),
                ('other_needs', models.TextField(blank=True, null=True, verbose_name='متطلبات أخري')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMemberDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=300, null=True, verbose_name='الأسم الثلاثي و القبيلة')),
                ('rel', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة')),
                ('familystatus', models.CharField(blank=True, max_length=300, null=True, verbose_name='الحالة الإجتماعية')),
                ('dateofbirth', models.CharField(blank=True, max_length=50, null=True, verbose_name='سنة الميلاد')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='المرحلة الدراسية')),
                ('job', models.CharField(blank=True, max_length=50, null=True, verbose_name='الوظيفة')),
                ('jobplace', models.CharField(blank=True, max_length=50, null=True, verbose_name='جهة العمل')),
                ('montlyincom', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبلغ الدخل الشهري')),
                ('loan', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبلغ القرض')),
                ('installment', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبلغ القسط الشهري')),
                ('loandesc', models.TextField(blank=True, null=True, verbose_name='سبب القرض')),
                ('healthstatus', models.TextField(blank=True, null=True, verbose_name='إسم الحالة الصحية')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inhouse_no', models.IntegerField(blank=True, null=True, verbose_name='عدد أفراد الأسرة المقيمين بالمنزل بصفة دائمة')),
                ('above18', models.IntegerField(blank=True, null=True, verbose_name='عدد الأبناء فوق سن ١٨ سنة')),
                ('study_elm', models.IntegerField(blank=True, null=True, verbose_name='عدد الطلبة في الجامعي')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loantype', models.IntegerField(blank=True, null=True, verbose_name='نوع القرض')),
                ('nameloner', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='إسم الجهة المناعة للقرض أو التمويل')),
                ('totalloan', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبلغ القرض')),
                ('instllament', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='القسط الشهري')),
                ('balanc', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='المبلغ المتبقي')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainIncom', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبلغ الراتب')),
                ('retirIncom', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبلغ التقاعد')),
                ('insuIncom', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='الضمان')),
                ('sctIncom', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبلغ فريق صلالة الخيري')),
                ('othersIncom', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبالغ أخرى')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housetype', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع السكن')),
                ('houseothers', models.CharField(blank=True, max_length=50, null=True, verbose_name='أخرى')),
                ('houseontype', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع حيازة السكن')),
                ('houseroom_n', models.IntegerField(blank=True, null=True, verbose_name='عددالغرف')),
                ('housersetting_n', models.IntegerField(blank=True, null=True, verbose_name='عددالمجالس')),
                ('housekitten_n', models.IntegerField(blank=True, null=True, verbose_name='عددالمطابخ')),
                ('housebath_n', models.IntegerField(blank=True, null=True, verbose_name='عددالحمامات')),
                ('houserent_t', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبالغ الإيجار الشهري')),
                ('houserent_r', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='المتبقي من الإيجار الشهري')),
                ('houseelec_r', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبالغ فاتورة الكهرباء')),
                ('housewater_r', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='مبالغ فاتورةالمياة')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyAttch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_app', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='رسالة طلب لفريق صلالة الخيري')),
                ('id_copy1', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='البطاقة الشخصية لصحاب الطلب')),
                ('id_copy2', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='البطاقة الشخصية أو الجواز لكل سكان المنزل')),
                ('dept_prove', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='إثبات المديونية')),
                ('workforce_prove', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='إثبات القوة العاملة')),
                ('incom_prove', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='كشف حساب بنكي لمدة ستة شهور')),
                ('coll_copy', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='نسخ من عقد الزواج/وثيقة الطلاق/شهادة وفاه/ملكية منزل/حكم بالسجن')),
                ('rent_prove', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='نسخة عقد إيجار مثبت')),
                ('medical_report', models.FileField(default='documents/None/no-img.jpg', upload_to='documents/%Y/%m/%d/%H/%M/%S/', verbose_name='تقرير طبي مفصل')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyAssit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assit_private_cars', models.IntegerField(blank=True, null=True, verbose_name='السيارات الخاصة')),
                ('assit_taxi', models.IntegerField(blank=True, null=True, verbose_name='تاكسي')),
                ('assit_school_bus', models.IntegerField(blank=True, null=True, verbose_name='حافلات المدرسة')),
                ('assit_gaz_car', models.IntegerField(blank=True, null=True, verbose_name='سيارات الغاز')),
                ('assit_others', models.TextField(null=True, verbose_name='أخرى')),
                ('fid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialforms.Family')),
            ],
        ),
    ]
